"""
Strategist agent for EcoPulse.
Acts as a top 1% LinkedIn Content Strategist and Environmental Engineer.
Transforms raw technical stitched text into clean, high-engagement, scannable LinkedIn posts with NO special characters/emojis.
"""

import json
import re
from llm import call_agent

from agents.instructor import QUALITY_CREDIBILITY_DIRECTIVE, clean_stock_transitions

SYSTEM_PROMPT = f"""You are a top 1% LinkedIn Content Strategist and Environmental Engineer specializing in Remote Sensing, GHG Accounting, and Environmental Infrastructure.

INSTRUCTOR MASTER DIRECTIVE (CRITICAL QUALITY & CREDIBILITY LAYER):
{QUALITY_CREDIBILITY_DIRECTIVE}

YOUR TASK:
Take the technical post draft generated by the writing agents and transform it into a high-engagement, viral, scroll-stopping LinkedIn post designed for ESG professionals, geospatial analysts, civil engineers, and energy sector executives.

STRICT FORMATTING & QUALITY RULES:
1. SOURCING RULE: Do NOT invent precise-sounding statistics. If a stat isn't from a real, named source in the draft, keep or rewrite it as a qualitative claim (e.g., "significantly higher risk").
2. CONCRETE ANCHORS: Preserve at least ONE named real-world example (company, plant type, regulation like CSRD/BRSR, or technology).
3. DE-TEMPLATE THE RHYTHM:
   - Vary paragraph length naturally (mix 1-line punches with 2-3 sentence paragraphs).
   - Do NOT default to uniform 1-sentence paragraphs throughout the entire post.
   - AVOID stock transition phrases like "This creates a paradox", "The hidden paradox", "Here is the catch", "This is the classic X-Y conflict in action", "In today's world", "As we navigate".
4. CLOSING QUESTION CHECK: The closing question MUST add a NEW angle, not restate the thesis already stated twice in the body. Pose a genuinely open, debatable question that climate tech, energy, and ESG professionals haven't already been told the answer to.
5. SPECIFICITY OVER GENERIC PHRASING: Replace generic thought-leader phrases ("dangerous architectural dependency", "digitizing X at a speed Y cannot match") with specific, falsifiable language.
6. NO SPECIAL CHARACTERS / NO EMOJIS: Use ONLY standard English alphanumeric characters (A-Z, a-z, 0-9), standard punctuation (. , : ; ? ! - ( ) / " '), and standard line breaks. No emojis, no markdown asterisks (**), no bullet symbols.

Return ONLY valid JSON:
{{
  "agent": "strategist",
  "output": {{
    "viral_post_text": "The fully formatted, high-engagement viral post text...",
    "word_count": 0
  }}
}}
"""

def clean_special_chars(text: str) -> str:
    """Strip out markdown asterisks, emojis, non-ASCII special characters, and stock transition phrases."""
    if not text:
        return ""
    # Clean stock transitions
    text = clean_stock_transitions(text)
    # Remove markdown bold/italic asterisks
    text = text.replace("**", "").replace("*", "")
    # Remove special Unicode bullets/emojis/symbols while preserving standard punctuation & numbers
    text = re.sub(r'[^\x00-\x7F]+', '', text)
    return text.strip()


def run(draft_text: str, topic: str, angle: str) -> dict:
    """Run the Strategist agent."""
    user_content = json.dumps({
        "draft_text": draft_text,
        "topic": topic,
        "angle": angle
    })
    result = call_agent(system_prompt=SYSTEM_PROMPT, user_content=user_content)
    
    # Post-process to guarantee clean text with zero special characters/emojis/stock transitions
    if isinstance(result, dict) and "output" in result and "viral_post_text" in result["output"]:
        cleaned = clean_special_chars(result["output"]["viral_post_text"])
        result["output"]["viral_post_text"] = cleaned
        result["output"]["word_count"] = len(cleaned.split())
        
    return result
