import os
import json
import base64
import requests
import urllib.request
import urllib.parse
from llm import call_agent

SYSTEM_PROMPT = """You are the Visualizer subagent for EcoPulse. You receive the Copywriter's \
post_text and image_brief. Generate an image prompt for a highly professional, modern, and visually stunning \
LinkedIn-friendly graphic.

Your prompt MUST be optimized for Flux / DALL-E 3. Follow these style rules:
- STYLE: Prefer sleek, premium 3D corporate graphic illustrations, modern flat vector art with a rich color palette, or high-end architectural/engineering photography.
- QUALITY KEYWORDS: Always append keywords like "premium 3D render, minimalist corporate design, vibrant color scheme, studio lighting, detailed, clean background, 8k resolution, trending on dribbble, professional LinkedIn graphic, no text, no watermarks".
- AVOID: Dull colors, low resolution, amateur designs, and stock photo clichés (e.g., no "hands holding a small green plant in soil").

Return ONLY valid JSON:
{
  "agent": "visualizer",
  "output": {
    "image_prompt": "...",
    "aspect_ratio": "1:1",
    "style_notes": "...",
    "text_overlay": null
  }
}"""


def _generate_prompt(copywriter_output: dict) -> dict:
    user_content = f"Post + brief:\n{json.dumps(copywriter_output, indent=2)}"
    return call_agent(SYSTEM_PROMPT, user_content, use_web_search=False)


def _render_image_openai(prompt: str, out_path: str) -> str:
    """Render via OpenAI Images API (dall-e-3). Set OPENAI_API_KEY to use this."""
    resp = requests.post(
        "https://api.openai.com/v1/images/generations",
        headers={"Authorization": f"Bearer {os.environ['OPENAI_API_KEY']}"},
        json={
            "model": "dall-e-3",
            "prompt": prompt,
            "size": "1024x1024",
            "response_format": "b64_json"
        },
        timeout=120,
    )
    resp.raise_for_status()
    b64 = resp.json()["data"][0]["b64_json"]
    with open(out_path, "wb") as f:
        f.write(base64.b64decode(b64))
    return out_path


def _render_image_stability(prompt: str, out_path: str) -> str:
    """Render via Stability AI. Set STABILITY_API_KEY to use this instead."""
    resp = requests.post(
        "https://api.stability.ai/v2beta/stable-image/generate/core",
        headers={
            "Authorization": f"Bearer {os.environ['STABILITY_API_KEY']}",
            "Accept": "image/*",
        },
        files={"none": ""},
        data={"prompt": prompt, "output_format": "png"},
        timeout=120,
    )
    resp.raise_for_status()
    with open(out_path, "wb") as f:
        f.write(resp.content)
    return out_path


def _render_image_imagen(prompt: str, out_path: str) -> str:
    """Render via Google Imagen 4 (imagen-4.0-generate-001) using GEMINI_API_KEY."""
    from google import genai
    api_key = os.environ.get("GEMINI_API_KEY")
    if not api_key:
        raise ValueError("GEMINI_API_KEY not found")
    client = genai.Client(api_key=api_key)
    result = client.models.generate_images(
        model='imagen-4.0-generate-001',
        prompt=prompt,
        config=dict(
            number_of_images=1,
            output_mime_type="image/jpeg",
            aspect_ratio="1:1"
        )
    )
    for generated_image in result.generated_images:
        with open(out_path, "wb") as f:
            f.write(generated_image.image.image_bytes)
        return out_path
    raise RuntimeError("No image generated by Google Imagen")


def _render_image_pollinations(prompt: str, out_path: str) -> str:
    """Free fallback image generator using Pollinations AI (Stable Diffusion model)."""
    encoded_query = urllib.parse.quote(prompt)
    url = f"https://image.pollinations.ai/prompt/{encoded_query}?width=1024&height=1024&nologo=true&model=stable-diffusion"
    req = urllib.request.Request(url, headers={'User-Agent': 'Mozilla/5.0'})
    with urllib.request.urlopen(req, timeout=45) as response:
        image_bytes = response.read()
    with open(out_path, "wb") as f:
        f.write(image_bytes)
    return out_path


def run(copywriter_output: dict, out_path: str = "state/latest_image.png") -> dict:
    result = _generate_prompt(copywriter_output)
    prompt = result["output"]["image_prompt"]

    # Append premium photographic style guidelines to ensure professional, realistic graphics
    style_suffix = (
        ", crisp DSLR architectural photography, corporate editorial style, "
        "natural sunlight, sharp focus on physical engineering media, "
        "real-world environmental aesthetic, no 3D renders, no cartoons, no text"
    )
    prompt = f"{prompt.rstrip('.')}{style_suffix}"

    image_path = ""
    # 1. Try OpenAI DALL-E 3 if key is present
    if os.environ.get("OPENAI_API_KEY"):
        try:
            image_path = _render_image_openai(prompt, out_path)
        except Exception:
            pass

    # 2. Try Google Imagen 4 using your existing Gemini key (Free on developer tier)
    if not image_path and os.environ.get("GEMINI_API_KEY"):
        try:
            image_path = _render_image_imagen(prompt, out_path)
        except Exception:
            pass

    # 3. Try Stability AI if key is present
    if not image_path and os.environ.get("STABILITY_API_KEY"):
        try:
            image_path = _render_image_stability(prompt, out_path)
        except Exception:
            pass

    # 4. Fallback to free Pollinations AI (Flux) with optimized prompt styling
    if not image_path:
        image_path = _render_image_pollinations(prompt, out_path)

    result["output"]["image_path"] = image_path
    return result
